version: "3.8"

services:
  db:
    image: postgres:14
    container_name: db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    container_name: agnos-backend
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/wait-for-postgres.sh"]
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db

volumes:
  pgdata:
